### ISSUE TITLE
`readFile "log.txt"` corrupts log.txt

### ISSUE THREAD

**Issue by chrismwendt** [litxio/ptghci#10]
```
ptghci> putStr =<< readFile "log.txt"
Sending response: ExecCaptureResponse {success = True, content = "readFile :: FilePath -> IO String"}
Got request Just (RequestExecStream {content = "putStr =<< readFile \"log.txt\""})
Sending response: ExecStreamResponse {success = True, errorMessage = Nothing, syncVal = 39}
Got request Just (RequestType {identifier = "\"log.txt\"", showHoleFits = False})
about to type "\"log.txt\""
finished typing:"log.txt" :: Data.String.IsString p => p

type req stdout: "log.txt" :: Data.String.IsString p => p
```

Somehow that command overwrites `log.txt` with that logging data. Is this some internal ptghci messaging? It definitely shouldn't corrupt the file.

**Comment by RichardWarfield** [comment]
Thanks for opening the issue.  Could you show the contents of your configuration file (ptghci.yaml in the project dir or or .ptghci.yaml in your home dir)?  This looks like the log file has been set to log.txt, in which case the behavior would be expected.

**Comment by chrismwendt** [comment]
Hmm, I don't have either of those files. It looks like `log.txt` is the default 

https://github.com/litxio/ptghci/blob/master/src/Language/Haskell/PtGhci/Config.hs#L36

**Comment by RichardWarfield** [comment]
Indeed, this looks like a bug.  I've pushed a fix.  Let me know if it solves the problem.

**Comment by chrismwendt** [comment]
After pulling I get

```
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "/Users/chrismwendt/github.com/litxio/ptghci/.stack-work/install/x86_64-osx/lts-13.17/8.6.4/share/x86_64-osx-ghc-8.6.4/ptghci-0.1.0.0/pybits/ptghci/app.py", line 29, in __init__
    self.history = ThreadedHistory(FileHistory(
NameError: name 'ThreadedHistory' is not defined
```

Seems to be caused by https://github.com/litxio/ptghci/commit/957fc8102f9598709ef7097d66ddde0d103deffb

Without that commit, it works. Closing this and opening a new issue for that one.
