### ISSUE TITLE
%history doesn't work

### ISSUE THREAD

**Issue by MatthewScholefield** [litxio/ptghci#25]
When I type something like `%history 54` to print the previously typed multiline input, I get the following:
```
λ [59]: %history 54                                                             
Out [59]: 
Not stopped at a breakpoint
```

**Comment by RichardWarfield** [comment]
The command is actually `%past`.  `%history` is a native GHCi command.

**Comment by MatthewScholefield** [comment]
Ohh, ok thanks!
