### ISSUE TITLE
Engine stopping

### ISSUE THREAD

**Issue by ShrykeWindgrace** [litxio/ptghci#6]
Hi!

When I run `ptghci`, it loads the prompt, then  immediately exits with
```
λ [1]: Leaving GHCi.
**Engine stopping**
**Engine stopping**
Exiting...
```

I have the following config:
- `ubuntu 16.04`
- `stack 1.9.3.1`
- `zsh`
- `libzmq 4.3.1` (installed manually, visible in $LD_LIBRARY_PATH)

Is there a way to determine where and how I need to tweak my config and/or environment variables for `ptghci` to work?

**Comment by RichardWarfield** [comment]
Strange.  Could you try setting `verbosity: Trace` and `logFile: ptghci.log` in ptghci.yaml, and let me know what gets written to the log file?

**Comment by ShrykeWindgrace** [comment]
Thanks for looking into this!
By your suggestion, with
```
% cat ptghci.yaml 
verbosity: Trace
logFile: ptghci.log
```
running `ptghci` gives 
```
% cat ptghci.log 
Got request Just RequestLoadMessages
Sending response: LoadMessagesResponse {success = True, messages = [LoadGhciVersion {loadVersion = "8.6.4"},LoadConfig {loadFile = "/tmp/haskell-stack-ghci/2a3bbd58/ghci-script"}]}
ZMQError { errno = 88, source = "getIntOpt", message = "Socket operation on non-socket" }
GHCi finished, exiting
AsyncCancelled
```

**Comment by RichardWarfield** [comment]
I'm pretty certain this is the same underlying issue as #5 so I'm going to close this in favor of discussion there.

**Comment by ShrykeWindgrace** [comment]
I agree, the symptoms look the same, let's continue there.
