### ISSUE TITLE
No such file or directory: 'hoogle'

### ISSUE THREAD

**Issue by mnn** [litxio/ptghci#7]
I am trying use `%hoogle`, but something is broken:

![Selection_058](https://user-images.githubusercontent.com/1975567/56912275-3b67f300-6aaf-11e9-84be-56532f80b400.png)

Running `stack hoogle panic` in same directory is working:

![Selection_059](https://user-images.githubusercontent.com/1975567/56912373-69e5ce00-6aaf-11e9-9ea6-5b5169165723.png)

Am I doing something wrong?

**Comment by RichardWarfield** [comment]
Thanks for the report!  

This should be fixed; could you try now? I've set things up such that `stack hoogle` is used by default when `stack` is on `PATH` (which is consistent with the way we call determine how to start `ghci`).  You can also override the hoogle command with the `hoogleCommand` setting.

**Comment by mnn** [comment]
That was fast :smiley:. Thank you, it works and looks great.

![Selection_060](https://user-images.githubusercontent.com/1975567/56960822-5a6b9100-6b52-11e9-87d0-41bba3b3f016.png)
