### ISSUE TITLE
Can't install, not finding specified version of zeromq4

### ISSUE THREAD

**Issue by JeffreyBenjaminBrown** [litxio/ptghci#8]
```
    Configuring zeromq4-haskell-0.7.0...
    Cabal-simple_mPHDZzAJ_2.4.0.1_ghc-8.6.4: The pkg-config package 'libzmq'
    version >=4.0 && <5.0 is required but it could not be found.
```

I'm installing on Ubuntu 18.04. My version of Stack is 1.9.3, which `stack upgrade` tells me is the latest. I was running these four steps from the README:
```
git clone https://github.com/litxio/ptghci
cd ptghci
pip3 install -r pybits/requirements.txt
stack install
```

The error happened in the fourth step.

**Comment by RichardWarfield** [comment]
You'll need to install ZeroMQ and other dependencies.  On Ubuntu the below command should do the trick:

`apt-get install pkg-config libpcre3-dev libzmq3-dev python3-dev python3-pip`
